AOSC-Dev/aosc-os-abbs

extra-admin/keepassx/autobuild/build
extra-admin/keepassx/autobuild/defines
extra-admin/keepassx/autobuild/patch
extra-admin/keepassx/spec

keepassx is a password manager that you can save username and password in an encrypted `.kdb` file, and be able to autofill the form, for example in a browser.
I don't know what branch I should open a pull request to, so I choose the branch `dev/new-packages` which seems the right place. (Both ab3/abbs and git/github are new to me.) I'm sorry if this don't meet the standard.

New package "keepassx"

---

extra-multimedia/smplayer/autobuild/build
extra-multimedia/smplayer/autobuild/defines
extra-multimedia/smplayer/spec
extra-shells/mksh/autobuild/alternatives
extra-shells/mksh/autobuild/build
extra-shells/mksh/autobuild/defines
extra-shells/mksh/spec

Bumped SMPlayer, mksh. Enabled alternatives for mksh, resolving issue #34.

Bump SMPlayer version to latest

---

extra-editors/wps-office/autobuild/README
extra-editors/wps-office/autobuild/build
extra-editors/wps-office/autobuild/defines
extra-editors/wps-office/autobuild/postinst
extra-editors/wps-office/autobuild/postrm
extra-editors/wps-office/autobuild/prerm
extra-editors/wps-office/spec
extra-i18n/wps-office-langpack/autobuild/build
extra-i18n/wps-office-langpack/autobuild/defines
extra-i18n/wps-office-langpack/spec
extra-i18n/wps-office-spellcheck/autobuild/build
extra-i18n/wps-office-spellcheck/autobuild/defines
extra-i18n/wps-office-spellcheck/spec

Upstream have renamed kingsoft-office to wps-office. Split the packages because they are meant to be split by upstream. Resolved issue #53.

Dev/new packages: added several split packages for wps-office

---

extra-tcl/tcllib/autobuild/defines
extra-tcl/tcllib/spec

My first trial. It's a super simple package.
tcllib is the standard Tcl library.
...
What should I say here?

Package request: tcllib

---

extra-tcl/tklib/autobuild/defines
extra-tcl/tklib/spec

Package request: tklib

---

extra-vcs/fossil/autobuild/defines
extra-vcs/fossil/spec

A new VCS!
It's more a portable GitHub than a VCS.

Package request: fossil

---

extra-devel/bam/autobuild/build
extra-devel/bam/autobuild/defines
extra-devel/bam/spec
extra-games/teeworlds/autobuild/build
extra-games/teeworlds/autobuild/defines
extra-games/teeworlds/autobuild/overrides/usr/share/applications/teeworlds.desktop
extra-games/teeworlds/spec

Teeworlds is a high-quality 2D shooting game, which is quite popular.
Bam is the build system used by Teeworlds, so it's also added.
Please don't mind the icon... It's not provided by the upstream so I simply picked a random one.

Package request: teeworlds, bam

---

extra-tcl/httpd-rivet/autobuild/defines
extra-tcl/httpd-rivet/spec

httpd-rivet: fix apache root

---

extra-libs/gnupg/autobuild/defines
extra-libs/gnupg/spec

gnupg: add dep 'npth'

---

extra-vcs/git/spec

git: bump to 2.6.0

---

extra-devel/capstone/autobuild/build
extra-devel/capstone/autobuild/defines
extra-devel/capstone/spec
extra-network/binwalk/autobuild/build
extra-network/binwalk/autobuild/defines
extra-network/binwalk/autobuild/patches/replace-java.patch
extra-network/binwalk/spec

New packages: capstone and binwalk.

Import capstone and binwalk

---

extra-network/cowpatty/autobuild/build
extra-network/cowpatty/autobuild/defines
extra-network/cowpatty/autobuild/patches/cowpatty-4.6-fixup16.patch
extra-network/cowpatty/spec
extra-network/macchanger/autobuild/defines
extra-network/macchanger/spec
extra-python/python2-pyx/autobuild/defines
extra-python/python2-pyx/spec
extra-python/python3-pyx/autobuild/defines
extra-python/python3-pyx/spec
extra-python/sqlalchemy/autobuild/build
extra-python/sqlalchemy/autobuild/defines
extra-python/sqlalchemy/spec

Import pyx and sqlalchemy

---

extra-network/pyrit/autobuild/defines
extra-network/pyrit/spec
extra-network/scapy/autobuild/defines
extra-network/scapy/spec
extra-python/gnuplot-py/autobuild/defines
extra-python/gnuplot-py/spec

I need someone to double check these packages for me...
And I want to know if our repository has openCL headers (req. by cpyrit-opencl) and complete CUDA development environment (cpyrit-cuda)...

Import new packages

---

extra-utils/hashID/autobuild/defines
extra-utils/hashID/spec
extra-utils/ollydbg/autobuild/build
extra-utils/ollydbg/autobuild/defines
extra-utils/ollydbg/autobuild/license.txt
extra-utils/ollydbg/autobuild/ollydbg.sh
extra-utils/ollydbg/autobuild/prepare
extra-utils/ollydbg/spec

hashID ollydbg: import

---

extra-multimedia/freepats/autobuild/build
extra-multimedia/freepats/autobuild/overrides/etc/timidity++/timidity-freepats.cfg

Not place in Timidy's path
Signed-off-by: liushuyu <liushuyu_011@163.com>

[Freepats] Fix paths

---

extra-libs/lash/autobuild/defines
extra-libs/lash/autobuild/patches/00-Split-docs-chapters.patch
extra-libs/lash/autobuild/postinst
extra-libs/lash/autobuild/prepare
extra-libs/lash/spec
extra-libs/liblo/autobuild/build
extra-libs/liblo/autobuild/defines
extra-libs/liblo/spec
extra-libs/mxml/autobuild/build
extra-libs/mxml/autobuild/defines
extra-libs/mxml/autobuild/prepare
extra-libs/mxml/spec
extra-multimedia/zynaddsubfx/autobuild/build
extra-multimedia/zynaddsubfx/autobuild/defines
extra-multimedia/zynaddsubfx/autobuild/patch
extra-multimedia/zynaddsubfx/spec

"I told u these are for Project Full LMMS on AOSC OS" --@liushuyu

[zynaddsubfx, lash, mxml, liblo] New

---

extra-creativity/lmms/autobuild/defines
extra-creativity/lmms/autobuild/patch
extra-creativity/lmms/spec
extra-libs/libgig/autobuild/defines
extra-libs/libgig/spec

[LMMS] Update to 1.1.90
[libgig] NEW

[LMMS] Update to 1.1.90

---

extra-themes/flat-plat-theme/autobuild/build
extra-themes/flat-plat-theme/autobuild/defines
extra-themes/flat-plat-theme/spec

w/o GDM themes and Chrome extensions.

flat-plat: import, 3.20.20160404

---

extra-multimedia/musicbox/autobuild/defines
extra-multimedia/musicbox/spec
extra-python/beautifulsoup4/autobuild/beyond
extra-python/beautifulsoup4/spec

CLI Version of Netease CloudMusic

musicbox: new, 0.2.3.2 & BeautifulSoup4: fix python3 error

---

extra-lua/luarocks/autobuild/build
extra-lua/luarocks/autobuild/defines
extra-lua/luarocks/spec

LuaRocks 2.4.1
A package manager for Lua modules.

luarocks: new, 2.4.1

---

extra-x11/xf86-video-siliconmotion/autobuild/defines
extra-x11/xf86-video-siliconmotion/autobuild/patches/0001-Modfix-IOPortBase.patch
extra-x11/xf86-video-siliconmotion/autobuild/patches/0002-Enable-crt-output-for-sm712.patch
extra-x11/xf86-video-siliconmotion/autobuild/patches/0003-Fix-loongson-2f-xv.patch
extra-x11/xf86-video-siliconmotion/spec

X.Org driver for siliconmotion. Required by some Loongson Lemote devices.

xf86-video-siliconmotion:new, 1.7.9

---

extra-scientific/ncbi-blast/autobuild/defines
extra-scientific/ncbi-blast/autobuild/prepare

Sorry for not testing it out... Not expecting that prepare was not executed before the building system was determined.

ncbi-blast+: fix

---

extra-scientific/bcftools/autobuild/defines
extra-scientific/bcftools/spec
extra-scientific/htslib/autobuild/defines
extra-scientific/htslib/spec
extra-scientific/samtools/autobuild/defines
extra-scientific/samtools/spec

Going to be useful for sequence analysis.

Add HTSlib packages

---

extra-network/danmaq/autobuild/defines
extra-network/danmaq/spec

Signed-off-by: Zamir SUN <sztsian@gmail.com>

danmaq: Add new package danmaq

---

extra-libs/libzip/autobuild/patches/CVE-2017-12858.patch
extra-libs/libzip/spec

https://github.com/nih-at/libzip/commit/2217022b7d1142738656d891e00b3d2d9179b796

libzip: fix CVE-2017-12858

---

extra-editors/neovim-qt/autobuild/defines
extra-editors/vis/autobuild/defines
extra-editors/xed/autobuild/defines
extra-games/pingus/autobuild/defines
extra-games/touchmegames/autobuild/defines
extra-network/genpac/autobuild/defines
extra-network/megasync/autobuild/defines
extra-network/pyrit/autobuild/defines
extra-network/scapy/autobuild/defines
extra-network/shadowsocks-qt5/autobuild/defines
extra-network/shadowsocks/autobuild/defines
extra-shells/dash/autobuild/defines
extra-shells/dgsh/autobuild/defines
extra-shells/elvish/autobuild/defines
extra-shells/fisherman/autobuild/defines

That's all I can find on aptitude for now... May have more.

Rename sec to maintain consistency

---

extra-admin/grub/autobuild/overrides/boot/grub/wallpaper.png
extra-admin/grub/autobuild/overrides/etc/default/grub

Customize GRUB for AOSC

---

extra-games/fortune-zh/autobuild/patches/0002-Move-data-file.patch
extra-games/fortune-zh/spec

There it goes, the second trial

Fix the inconsistency between fortune-mod and this regarding cookiedir

---

extra-wm/fluxbox/autobuild/patches/000-more-terminals.patch
extra-wm/fluxbox/autobuild/postinst
extra-wm/fluxbox/spec

Hey Fluxbox how can you assume that I have either GNome or KDE already installed?!

Add postinst with patch to allow detection of other terminals

---

extra-admin/grub/autobuild/amd64/build
extra-admin/grub/spec

grub: Add coreboot platform for amd64
